/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package geni;

/**
 *
 * @author PCuser
 */
public class pokedex {
    //base stats will be accessible here, all we will need is a class that will have an Identifier and that will return all data needed.
    public enum Pokemon {
        Bulbasaur(new int[]{45,49,65,65,45}), 
        Ivysaur, 
        Venusaur, 
        Charmander, 
        Charmeleon, 
        Charizard, 
        Squirtle, 
        Wartortle, 
        Blastoise, 
        Caterpie, 
        Metapod, 
        Butterfree, 
        Weedle, 
        Kakuna, 
        Beedrill, 
        Pidgey, 
        Pidgeotto, 
        Pidgeot, 
        Rattata, 
        Raticate, 
        Spearow, 
        Fearow, 
        Ekans, 
        Arbok, 
        Pikachu, 
        Raichu, 
        Sandshrew, 
        Sandslash, 
        Nidoran, 
        Nidorina, 
        Nidoqueen, 
        Nidorino,
        Nidoking, 
        Clefairy, 
        Clefable, 
        Vulpix, 
        Ninetales, 
        Jigglypuff, 
        Wigglytuff, 
        Zubat, 
        Golbat, 
        Oddish, 
        Gloom, 
        Vileplume, 
        Paras, 
        Parasect, 
        Venonat, 
        Venomoth, 
        Diglett, 
        Dugtrio, 
        Meowth, 
        Persian, 
        Psyduck, 
        Golduck, 
        Mankey, 
        Primeape, 
        Growlithe, 
        Arcanine, 
        Poliwag, 
        Poliwhirl, 
        Poliwrath, 
        Abra, 
        Kadabra, 
        Alakazam, 
        Machop, 
        Machoke, 
        Machamp, 
        Bellsprout, 
        Weepinbell, 
        Victreebel, 
        Tentacool, 
        Tentacruel, 
        Geodude, 
        Graveler, 
        Golem, 
        Ponyta, 
        Rapidash, 
        Slowpoke, 
        Slowbro, 
        Magnemite, 
        Magneton, 
        Farfetchd, 
        Doduo, 
        Dodrio, 
        Seel, 
        Dewgong, 
        Grimer, 
        Muk, 
        Shellder, 
        Cloyster, 
        Gastly, 
        Haunter, 
        Gengar, 
        Onix, 
        Drowzee, 
        Hypno, 
        Krabby, 
        Kingler, 
        Voltorb,
        Electrode, 
        Exeggcute, 
        Exeggutor, 
        Cubone, 
        Marowak, 
        Hitmonlee, 
        Hitmonchan, 
        Lickitung, 
        Koffing, 
        Weezing, 
        Rhyhorn, 
        Rhydon, 
        Chansey, 
        Tangela, 
        Kangaskhan, 
        Horsea, 
        Seadra, 
        Goldeen, 
        Seaking, 
        Staryu, 
        Starmie, 
        MrMime, 
        Scyther, 
        Jynx, 
        Electabuzz, 
        Magmar, 
        Pinsir, 
        Tauros, 
        Magikarp, 
        Gyarados, 
        Lapras, 
        Ditto, 
        Eevee, 
        Vaporeon, 
        Jolteon, 
        Flareon, 
        Porygon, 
        Omanyte, 
        Omastar, 
        Kabuto, 
        Kabutops, 
        Aerodactyl, 
        Snorlax, 
        Articuno, 
        Zapdos, 
        Moltres, 
        Dratini, 
        Dragonair, 
        Dragonite, 
        Mewtwo, 
        Mew;
        
    }
    
    public enum type {
        Normal(new double[]{1,1,1,1,1,1,1,1,1,1,1,1,0.5,0,1}),
        Fire(new double[]{1,0.5,0.5,1,2,2,1,1,1,1,1,2,0.5,1,0.5}),
        Water(new double[]{1,2,0.5,1,0.5,1,1,1,2,1,1,1,2,1,0.5}),
        Electric(new double[]{1,1,2,0.5,0.5,1,1,1,0,2,1,1,1,1,0.5}),
        Grass(new double[]{1,0.5,2,1,0.5,1,1,0.5,2,0.5,1,0.5,2,1,0.5}),
        Ice(new double[]{1,1,0.5,1,2,0.5,1,1,2,2,1,1,1,1,2}),
        Fighting(new double[]{2,1,1,1,1,2,1,0.5,1,0.5,0.5,0.5,2,0,1}),
        Poison(new double[]{1,1,1,1,2,1,1,0.5,0.5,1,1,2,0.5,0.5}),
        Ground(new double[]{1,2,1,2,0.5,1,1,2,1,0,1,0.5,2,1,1}),
        Flying(new double[]{1,1,1,0.5,2,1,2,1,1,1,1,2,0.5,1,1}),
        Psychic(new double[]{1,1,1,1,1,1,2,2,1,1,0.5,1,1,1,1}),
        Bug(new double[]{1,0.5,1,1,2,1,0.5,2,1,0.5,2,1,1,0.5,1}),
        Rock(new double[]{1,2,1,1,1,2,0.5,1,0.5,2,1,2,1,1,1}),
        Ghost(new double[]{0,1,1,1,1,1,1,1,1,1,0,1,1,2,1}),
        Dragon(new double[]{1,1,1,1,1,1,1,1,1,1,1,1,1,1,2});
        
        private final double[] battleCoefficients;
        private type(double[] battleCoefficients){
            this.battleCoefficients = battleCoefficients;
        }
        
        private double[] getBattleCoefficients() {
            return this.battleCoefficients;
        }
    }
}
